name: Linters

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  suite:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - uses: actions/checkout@v2
      - name: Pre-install
        run: npm run preinstall
      - name: Install dependencies
        run: npm install
      - name: Run linters
        run: npm run lint
